---
version: '2'
services:
  confluent-zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  confluent-kafka:
    image: confluentinc/cp-kafka:3.2.0
    network_mode: host
    depends_on:
      - confluent-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_MACHINE_IP}:29092
